version: "3.7"

services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${APP_PORT}:${APP_PORT}
  nginx:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./containers/nginx/conf:/etc/nginx/templates
      - ./logs/:/var/log/nginx/