version: "3.7"

services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${APP_PORT}:${APP_PORT}